name = "SIMPLE"
version = "1.4.0"
license = "MIT"
author = "Christopher Albert"
maintainer = "albert@tugraz.at"
copyright = "Copyright 2025, Plasma Physics at TU Graz"

[dependencies]
libneo = { git = "https://github.com/itpplasma/libneo.git", rev = "afa0e4243e5e3f3e41110960f19cd0f340834988" }
openmp = "*"
blas = "*"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"
