#!/usr/bin/env python3
"""End-to-end test: VMEC-Boozer vs Boozer chartmap confined fractions.

Two fully isolated simple.x runs with identical particles:
1. VMEC path: simple.x reads wout.nc, computes Boozer internally
2. Chartmap path: simple.x reads boozer_chartmap.nc, no VMEC at all

Particle initial conditions are generated by the VMEC run, then converted
to Boozer/chartmap reference coordinates for the chartmap run.

Tests multiple equilibria and longer trace times.
"""

import os
import sys
import shutil
import subprocess
import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BUILD_DIR = os.path.join(os.path.dirname(os.path.dirname(SCRIPT_DIR)), "build")
SIMPLE_X = os.path.join(BUILD_DIR, "simple.x")
TOOL_X = os.path.join(BUILD_DIR, "test", "tests", "export_boozer_chartmap_tool.x")
TEST_DATA = os.path.join(os.path.dirname(SCRIPT_DIR), "test_data")

EQUILIBRIA = [
    {
        "name": "QA",
        "wout": os.path.join(TEST_DATA, "wout.nc"),
        "trace_time": "1d-2",
        "facE_al": "1.0d0",
    },
    {
        "name": "NCSX",
        "wout": os.path.join(TEST_DATA, "wout_ncsx.nc"),
        "trace_time": "1d-2",
        "facE_al": "100.0d0",
    },
]


def simple_in_vmec(wout_name, trace_time, facE_al):
    return f"""\
&config
multharm = 3
contr_pp = -1e10
trace_time = {trace_time}
sbeg = 0.3d0
ntestpart = 32
netcdffile = '{wout_name}'
isw_field_type = 2
deterministic = .True.
integmode = 1
facE_al = {facE_al}
/
"""


def simple_in_chartmap(trace_time, facE_al):
    return f"""\
&config
multharm = 3
contr_pp = -1e10
trace_time = {trace_time}
sbeg = 0.3d0
ntestpart = 32
field_input = 'boozer_chartmap.nc'
coord_input = 'boozer_chartmap.nc'
isw_field_type = 2
deterministic = .True.
integmode = 1
startmode = 2
facE_al = {facE_al}
/
"""


def run_cmd(cmd, cwd, label, timeout=600):
    print(f"  [{label}] {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout)
    if result.returncode != 0:
        print(f"  FAILED: {label}")
        print(result.stdout[-2000:] if result.stdout else "")
        print(result.stderr[-2000:] if result.stderr else "")
        return False
    return True


def run_single_equilibrium(eq, outdir):
    name = eq["name"]
    wout = eq["wout"]
    trace_time = eq["trace_time"]
    facE_al = eq["facE_al"]

    if not os.path.exists(wout):
        print(f"  Skipping {name}: {wout} not found")
        return True

    eq_dir = os.path.join(outdir, name)
    vmec_dir = os.path.join(eq_dir, "vmec_run")
    chartmap_dir = os.path.join(eq_dir, "chartmap_run")
    os.makedirs(vmec_dir)
    os.makedirs(chartmap_dir)

    wout_name = os.path.basename(wout)

    # Step 1: VMEC-Boozer
    print(f"  [{name}] Step 1: VMEC-Boozer path...")
    shutil.copy(wout, os.path.join(vmec_dir, wout_name))
    with open(os.path.join(vmec_dir, "simple.in"), "w") as f:
        f.write(simple_in_vmec(wout_name, trace_time, facE_al))

    if not run_cmd([SIMPLE_X], cwd=vmec_dir, label=f"{name} VMEC"):
        return False

    cf_vmec = os.path.join(vmec_dir, "confined_fraction.dat")
    start_vmec = os.path.join(vmec_dir, "start.dat")
    assert os.path.exists(cf_vmec), f"{name}: confined_fraction.dat not produced"
    assert os.path.exists(start_vmec), f"{name}: start.dat not produced"

    # Step 2: Export chartmap + convert start.dat
    print(f"  [{name}] Step 2: Exporting chartmap...")
    chartmap_nc = os.path.join(chartmap_dir, "boozer_chartmap.nc")
    start_boozer = os.path.join(chartmap_dir, "start.dat")

    if not run_cmd([TOOL_X, os.path.join(vmec_dir, wout_name), chartmap_nc,
                    start_vmec, start_boozer],
                   cwd=chartmap_dir, label=f"{name} export"):
        return False

    # Step 3: Chartmap-only
    print(f"  [{name}] Step 3: Chartmap-only path...")
    with open(os.path.join(chartmap_dir, "simple.in"), "w") as f:
        f.write(simple_in_chartmap(trace_time, facE_al))

    if not run_cmd([SIMPLE_X], cwd=chartmap_dir, label=f"{name} chartmap"):
        return False

    cf_chartmap = os.path.join(chartmap_dir, "confined_fraction.dat")
    assert os.path.exists(cf_chartmap), f"{name}: confined_fraction.dat not produced"

    # Step 4: Compare
    data_vmec = np.loadtxt(cf_vmec)
    data_chartmap = np.loadtxt(cf_chartmap)

    n = min(len(data_vmec), len(data_chartmap))
    data_vmec = data_vmec[:n]
    data_chartmap = data_chartmap[:n]

    t = data_vmec[:, 0]
    pass_v, trap_v = data_vmec[:, 1], data_vmec[:, 2]
    pass_c, trap_c = data_chartmap[:, 1], data_chartmap[:, 2]
    total_v = pass_v + trap_v
    total_c = pass_c + trap_c

    max_diff_total = np.max(np.abs(total_v - total_c))
    max_diff_pass = np.max(np.abs(pass_v - pass_c))
    max_diff_trap = np.max(np.abs(trap_v - trap_c))

    print(f"  [{name}] max |total diff| = {max_diff_total:.6e}")
    print(f"  [{name}] max |pass diff|  = {max_diff_pass:.6e}")
    print(f"  [{name}] max |trap diff|  = {max_diff_trap:.6e}")

    # Plot
    plot_comparison(eq_dir, name, t, total_v, total_c, pass_v, pass_c, trap_v, trap_c)

    npart = data_vmec[0, 3]
    tol = 1.0 / npart
    if max_diff_total > tol:
        print(f"  [{name}] FAIL: total confined differs by {max_diff_total:.6e} > {tol:.6e}")
        return False

    print(f"  [{name}] PASS")
    return True


def plot_comparison(outdir, name, t, total_v, total_c, pass_v, pass_c, trap_v, trap_c):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 3, figsize=(15, 4.5))

    ax = axes[0]
    ax.plot(t * 1e3, total_v, "b-", lw=1.5, label="VMEC-Boozer")
    ax.plot(t * 1e3, total_c, "r--", lw=1.5, label="Chartmap")
    ax.set_xlabel("time [ms]")
    ax.set_ylabel("confined fraction")
    ax.set_title("Total confined")
    ax.legend()
    ax.set_ylim(-0.05, 1.05)

    ax = axes[1]
    ax.plot(t * 1e3, pass_v, "b-", lw=1.5, label="VMEC passing")
    ax.plot(t * 1e3, pass_c, "r--", lw=1.5, label="Chartmap passing")
    ax.plot(t * 1e3, trap_v, "b-", lw=1, alpha=0.5, label="VMEC trapped")
    ax.plot(t * 1e3, trap_c, "r--", lw=1, alpha=0.5, label="Chartmap trapped")
    ax.set_xlabel("time [ms]")
    ax.set_ylabel("confined fraction")
    ax.set_title("Passing + Trapped")
    ax.legend(fontsize=8)
    ax.set_ylim(-0.05, 1.05)

    ax = axes[2]
    ax.semilogy(t * 1e3, np.abs(total_v - total_c) + 1e-16, "k-", lw=1)
    ax.set_xlabel("time [ms]")
    ax.set_ylabel("|difference|")
    ax.set_title("Confined fraction difference")

    fig.suptitle(f"E2E: VMEC-Boozer vs Chartmap ({name})", fontsize=14)
    fig.tight_layout()
    outpath = os.path.join(outdir, f"e2e_{name}.png")
    fig.savefig(outpath, dpi=150)
    print(f"  Saved {outpath}")


def main():
    for path, label in [(SIMPLE_X, "simple.x"), (TOOL_X, "export tool")]:
        if not os.path.exists(path):
            print(f"Missing {label}: {path}")
            sys.exit(1)

    outdir = "/tmp/boozer_chartmap_e2e"
    if os.path.exists(outdir):
        shutil.rmtree(outdir)
    os.makedirs(outdir)

    all_pass = True
    for eq in EQUILIBRIA:
        print(f"\n=== {eq['name']} (trace_time={eq['trace_time']}) ===")
        if not run_single_equilibrium(eq, outdir):
            all_pass = False

    print()
    if all_pass:
        print("ALL EQUILIBRIA PASSED")
    else:
        print("SOME EQUILIBRIA FAILED")
        sys.exit(1)


if __name__ == "__main__":
    main()
