#!/usr/bin/env python3
"""End-to-end test: VMEC-Boozer vs Boozer chartmap confined fractions.

Two fully isolated simple.x runs:
1. VMEC path: simple.x reads wout.nc, computes Boozer internally
2. Chartmap path: simple.x reads boozer_chartmap.nc, no VMEC at all

Particle initial conditions are generated by the VMEC run, then converted
to Boozer/chartmap reference coordinates for the chartmap run.
"""

import os
import sys
import shutil
import subprocess
import tempfile
import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BUILD_DIR = os.path.join(os.path.dirname(os.path.dirname(SCRIPT_DIR)), "build")
SIMPLE_X = os.path.join(BUILD_DIR, "simple.x")
TOOL_X = os.path.join(BUILD_DIR, "test", "tests", "export_boozer_chartmap_tool.x")
TEST_DATA = os.path.join(os.path.dirname(SCRIPT_DIR), "test_data")
WOUT_FILE = os.path.join(TEST_DATA, "wout.nc")

SIMPLE_IN_VMEC = """\
&config
multharm = 3
contr_pp = -1e10
trace_time = 1d-4
sbeg = 0.3d0
ntestpart = 32
netcdffile = 'wout.nc'
isw_field_type = 2
deterministic = .True.
integmode = 1
/
"""

SIMPLE_IN_CHARTMAP = """\
&config
multharm = 3
contr_pp = -1e10
trace_time = 1d-4
sbeg = 0.3d0
ntestpart = 32
field_input = 'boozer_chartmap.nc'
coord_input = 'boozer_chartmap.nc'
isw_field_type = 2
deterministic = .True.
integmode = 1
startmode = 2
/
"""


def run_cmd(cmd, cwd, label):
    print(f"  [{label}] {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=300)
    if result.returncode != 0:
        print(f"  FAILED: {label}")
        print(result.stdout[-2000:] if result.stdout else "")
        print(result.stderr[-2000:] if result.stderr else "")
        sys.exit(1)
    return result


def main():
    # Check prerequisites
    for path, name in [(SIMPLE_X, "simple.x"), (TOOL_X, "export tool"), (WOUT_FILE, "wout.nc")]:
        if not os.path.exists(path):
            print(f"Missing {name}: {path}")
            sys.exit(1)

    outdir = "/tmp/boozer_chartmap_e2e"
    vmec_dir = os.path.join(outdir, "vmec_run")
    chartmap_dir = os.path.join(outdir, "chartmap_run")

    # Clean and create directories
    if os.path.exists(outdir):
        shutil.rmtree(outdir)
    os.makedirs(vmec_dir)
    os.makedirs(chartmap_dir)

    # =========================================================
    # Step 1: Run VMEC-Boozer path
    # =========================================================
    print("Step 1: Running VMEC-Boozer path...")
    shutil.copy(WOUT_FILE, os.path.join(vmec_dir, "wout.nc"))
    with open(os.path.join(vmec_dir, "simple.in"), "w") as f:
        f.write(SIMPLE_IN_VMEC)

    run_cmd([SIMPLE_X], cwd=vmec_dir, label="simple.x VMEC")

    cf_vmec = os.path.join(vmec_dir, "confined_fraction.dat")
    start_vmec = os.path.join(vmec_dir, "start.dat")
    assert os.path.exists(cf_vmec), "confined_fraction.dat not produced"
    assert os.path.exists(start_vmec), "start.dat not produced"
    print("  -> confined_fraction.dat and start.dat generated")

    # =========================================================
    # Step 2: Export Boozer chartmap and convert start.dat
    # =========================================================
    print("Step 2: Exporting Boozer chartmap and converting start.dat...")
    chartmap_nc = os.path.join(chartmap_dir, "boozer_chartmap.nc")
    start_boozer = os.path.join(chartmap_dir, "start.dat")

    run_cmd([TOOL_X, os.path.join(vmec_dir, "wout.nc"), chartmap_nc,
             start_vmec, start_boozer],
            cwd=chartmap_dir, label="export tool")

    assert os.path.exists(chartmap_nc), "chartmap not produced"
    assert os.path.exists(start_boozer), "start_boozer.dat not produced"
    print("  -> boozer_chartmap.nc and converted start.dat generated")

    # =========================================================
    # Step 3: Run chartmap-only path (NO VMEC)
    # =========================================================
    print("Step 3: Running chartmap-only path...")
    with open(os.path.join(chartmap_dir, "simple.in"), "w") as f:
        f.write(SIMPLE_IN_CHARTMAP)

    run_cmd([SIMPLE_X], cwd=chartmap_dir, label="simple.x chartmap")

    cf_chartmap = os.path.join(chartmap_dir, "confined_fraction.dat")
    assert os.path.exists(cf_chartmap), "confined_fraction.dat not produced"
    print("  -> confined_fraction.dat generated")

    # =========================================================
    # Step 4: Compare confined fractions
    # =========================================================
    print("Step 4: Comparing confined fractions...")
    data_vmec = np.loadtxt(cf_vmec)
    data_chartmap = np.loadtxt(cf_chartmap)

    n = min(len(data_vmec), len(data_chartmap))
    data_vmec = data_vmec[:n]
    data_chartmap = data_chartmap[:n]

    t_v = data_vmec[:, 0]
    pass_v = data_vmec[:, 1]
    trap_v = data_vmec[:, 2]
    total_v = pass_v + trap_v

    t_c = data_chartmap[:, 0]
    pass_c = data_chartmap[:, 1]
    trap_c = data_chartmap[:, 2]
    total_c = pass_c + trap_c

    max_diff_total = np.max(np.abs(total_v - total_c))
    max_diff_pass = np.max(np.abs(pass_v - pass_c))
    max_diff_trap = np.max(np.abs(trap_v - trap_c))

    print(f"  max |total_vmec - total_chartmap| = {max_diff_total:.6e}")
    print(f"  max |pass_vmec - pass_chartmap|   = {max_diff_pass:.6e}")
    print(f"  max |trap_vmec - trap_chartmap|   = {max_diff_trap:.6e}")

    # Save comparison data
    np.savetxt(os.path.join(outdir, "comparison.dat"),
               np.column_stack([t_v, total_v, total_c, pass_v, pass_c, trap_v, trap_c]),
               header="time total_vmec total_chartmap pass_vmec pass_chartmap trap_vmec trap_chartmap")

    # =========================================================
    # Step 5: Plot
    # =========================================================
    print("Step 5: Generating plots...")
    plot_comparison(outdir, t_v, total_v, total_c, pass_v, pass_c, trap_v, trap_c)

    # =========================================================
    # Step 6: Pass/Fail
    # =========================================================
    npart = data_vmec[0, 3]
    tol = 6.0 / npart  # allow up to 6 particles difference (resolution effect)
    if max_diff_total > tol:
        print(f"FAIL: confined fraction differs by {max_diff_total:.6e} > {tol:.6e}")
        sys.exit(1)
    else:
        print(f"PASS: confined fractions match within {tol:.6e}")


def plot_comparison(outdir, t, total_v, total_c, pass_v, pass_c, trap_v, trap_c):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 3, figsize=(15, 4.5))

    ax = axes[0]
    ax.plot(t * 1e3, total_v, "b-", lw=1.5, label="VMEC-Boozer")
    ax.plot(t * 1e3, total_c, "r--", lw=1.5, label="Chartmap")
    ax.set_xlabel("time [ms]")
    ax.set_ylabel("confined fraction")
    ax.set_title("Total confined")
    ax.legend()
    ax.set_ylim(-0.05, 1.05)

    ax = axes[1]
    ax.plot(t * 1e3, pass_v, "b-", lw=1.5, label="VMEC passing")
    ax.plot(t * 1e3, pass_c, "r--", lw=1.5, label="Chartmap passing")
    ax.plot(t * 1e3, trap_v, "b-", lw=1, alpha=0.5, label="VMEC trapped")
    ax.plot(t * 1e3, trap_c, "r--", lw=1, alpha=0.5, label="Chartmap trapped")
    ax.set_xlabel("time [ms]")
    ax.set_ylabel("confined fraction")
    ax.set_title("Passing + Trapped")
    ax.legend(fontsize=8)
    ax.set_ylim(-0.05, 1.05)

    ax = axes[2]
    ax.semilogy(t * 1e3, np.abs(total_v - total_c) + 1e-16, "k-", lw=1)
    ax.set_xlabel("time [ms]")
    ax.set_ylabel("|difference|")
    ax.set_title("Confined fraction difference")

    fig.suptitle("E2E: VMEC-Boozer vs Boozer Chartmap", fontsize=14)
    fig.tight_layout()
    outpath = os.path.join(outdir, "e2e_confined_fraction.png")
    fig.savefig(outpath, dpi=150)
    print(f"  Saved {outpath}")


if __name__ == "__main__":
    main()
