#!/usr/bin/env python3
"""End-to-end test: VMEC-Boozer vs Boozer chartmap confined fractions.

Two fully isolated simple.x runs with identical particles:
1. VMEC path: simple.x reads wout.nc, computes Boozer internally
2. Chartmap path: simple.x reads boozer_chartmap.nc, no VMEC at all

Particle initial conditions are generated by the VMEC run, then converted
to Boozer/chartmap reference coordinates for the chartmap run.

Tests multiple equilibria and longer trace times.
"""

import os
import sys
import shutil
import subprocess
import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BUILD_DIR = os.path.join(os.path.dirname(os.path.dirname(SCRIPT_DIR)), "build")
SIMPLE_X = os.path.join(BUILD_DIR, "simple.x")
TOOL_X = os.path.join(BUILD_DIR, "test", "tests", "export_boozer_chartmap_tool.x")
TEST_DATA = os.path.join(os.path.dirname(SCRIPT_DIR), "test_data")

EQUILIBRIA = [
    {
        "name": "QA",
        "wout": os.path.join(TEST_DATA, "wout.nc"),
        "gvec_chartmap": os.path.join(TEST_DATA, "wout_qa.gvec.chartmap.nc"),
        "trace_time": "1d-2",
        "facE_al": "1.0d0",
    },
    {
        "name": "NCSX",
        "wout": os.path.join(TEST_DATA, "wout_ncsx.nc"),
        "gvec_chartmap": None,
        "trace_time": "1d-2",
        "facE_al": "100.0d0",
    },
]


def simple_in_vmec(wout_name, trace_time, facE_al):
    return f"""\
&config
multharm = 3
contr_pp = -1e10
trace_time = {trace_time}
sbeg = 0.3d0
ntestpart = 32
netcdffile = '{wout_name}'
isw_field_type = 2
deterministic = .True.
integmode = 1
facE_al = {facE_al}
/
"""


def simple_in_chartmap(chartmap_name, trace_time, facE_al):
    return f"""\
&config
multharm = 3
contr_pp = -1e10
trace_time = {trace_time}
sbeg = 0.3d0
ntestpart = 32
field_input = '{chartmap_name}'
coord_input = '{chartmap_name}'
isw_field_type = 2
deterministic = .True.
integmode = 1
startmode = 2
facE_al = {facE_al}
/
"""


def run_cmd(cmd, cwd, label, timeout=600):
    print(f"  [{label}] {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout)
    if result.returncode != 0:
        print(f"  FAILED: {label}")
        print(result.stdout[-2000:] if result.stdout else "")
        print(result.stderr[-2000:] if result.stderr else "")
        return False
    return True


def run_single_equilibrium(eq, outdir):
    name = eq["name"]
    wout = eq["wout"]
    gvec_chartmap = eq["gvec_chartmap"]
    trace_time = eq["trace_time"]
    facE_al = eq["facE_al"]

    if not os.path.exists(wout):
        print(f"  Skipping {name}: {wout} not found")
        return True

    eq_dir = os.path.join(outdir, name)
    vmec_dir = os.path.join(eq_dir, "vmec_run")
    chartmap_dir = os.path.join(eq_dir, "vmec_chartmap_run")
    gvec_dir = os.path.join(eq_dir, "gvec_chartmap_run")
    os.makedirs(vmec_dir)
    os.makedirs(chartmap_dir)
    if gvec_chartmap and os.path.exists(gvec_chartmap):
        os.makedirs(gvec_dir)

    wout_name = os.path.basename(wout)

    # Step 1: VMEC-Boozer
    print(f"  [{name}] Step 1: VMEC-Boozer path...")
    shutil.copy(wout, os.path.join(vmec_dir, wout_name))
    with open(os.path.join(vmec_dir, "simple.in"), "w") as f:
        f.write(simple_in_vmec(wout_name, trace_time, facE_al))

    if not run_cmd([SIMPLE_X], cwd=vmec_dir, label=f"{name} VMEC"):
        return False

    cf_vmec = os.path.join(vmec_dir, "confined_fraction.dat")
    start_vmec = os.path.join(vmec_dir, "start.dat")
    assert os.path.exists(cf_vmec), f"{name}: confined_fraction.dat not produced"
    assert os.path.exists(start_vmec), f"{name}: start.dat not produced"

    # Step 2: Export chartmap + convert start.dat
    print(f"  [{name}] Step 2: Exporting chartmap...")
    chartmap_nc = os.path.join(chartmap_dir, "boozer_chartmap.nc")
    start_boozer = os.path.join(chartmap_dir, "start.dat")

    if not run_cmd([TOOL_X, os.path.join(vmec_dir, wout_name), chartmap_nc,
                    start_vmec, start_boozer],
                   cwd=chartmap_dir, label=f"{name} export"):
        return False

    # Step 3: Chartmap-only
    print(f"  [{name}] Step 3: VMEC chartmap-only path...")
    with open(os.path.join(chartmap_dir, "simple.in"), "w") as f:
        f.write(simple_in_chartmap("boozer_chartmap.nc", trace_time, facE_al))

    if not run_cmd([SIMPLE_X], cwd=chartmap_dir, label=f"{name} VMEC chartmap"):
        return False

    cf_chartmap = os.path.join(chartmap_dir, "confined_fraction.dat")
    assert os.path.exists(cf_chartmap), f"{name}: confined_fraction.dat not produced"

    series = {
        "VMEC-Boozer": np.loadtxt(cf_vmec),
        "VMEC chartmap": np.loadtxt(cf_chartmap),
    }

    if gvec_chartmap and os.path.exists(gvec_chartmap):
        print(f"  [{name}] Step 4: GVEC chartmap-only path...")
        shutil.copy(gvec_chartmap, os.path.join(gvec_dir, "boozer_chartmap.nc"))
        shutil.copy(start_boozer, os.path.join(gvec_dir, "start.dat"))
        with open(os.path.join(gvec_dir, "simple.in"), "w") as f:
            f.write(simple_in_chartmap("boozer_chartmap.nc", trace_time, facE_al))
        if not run_cmd([SIMPLE_X], cwd=gvec_dir, label=f"{name} GVEC chartmap"):
            return False
        cf_gvec = os.path.join(gvec_dir, "confined_fraction.dat")
        assert os.path.exists(cf_gvec), f"{name}: GVEC confined_fraction.dat not produced"
        series["GVEC chartmap"] = np.loadtxt(cf_gvec)

    # Step 5: Compare
    min_len = min(len(data) for data in series.values())
    for key in list(series):
        series[key] = series[key][:min_len]

    ref = series["VMEC-Boozer"]
    t = ref[:, 0]
    npart = ref[0, 3]
    tol = 1.0 / npart

    totals = {}
    passings = {}
    trappeds = {}
    for key, data in series.items():
        passings[key] = data[:, 1]
        trappeds[key] = data[:, 2]
        totals[key] = passings[key] + trappeds[key]

    max_diff_total = 0.0
    max_diff_pass = 0.0
    max_diff_trap = 0.0
    labels = list(series)
    for i, left in enumerate(labels):
        for right in labels[i + 1:]:
            diff_total = np.max(np.abs(totals[left] - totals[right]))
            diff_pass = np.max(np.abs(passings[left] - passings[right]))
            diff_trap = np.max(np.abs(trappeds[left] - trappeds[right]))
            print(f"  [{name}] max |total diff| {left} vs {right} = {diff_total:.6e}")
            print(f"  [{name}] max |pass diff|  {left} vs {right} = {diff_pass:.6e}")
            print(f"  [{name}] max |trap diff|  {left} vs {right} = {diff_trap:.6e}")
            max_diff_total = max(max_diff_total, diff_total)
            max_diff_pass = max(max_diff_pass, diff_pass)
            max_diff_trap = max(max_diff_trap, diff_trap)

    plot_comparison(eq_dir, name, t, totals, passings, trappeds)

    if max_diff_total > tol or max_diff_pass > tol or max_diff_trap > tol:
        print(
            f"  [{name}] FAIL: pairwise confined-fraction disagreement exceeds {tol:.6e}"
        )
        return False

    print(f"  [{name}] PASS")
    return True


def plot_comparison(outdir, name, t, totals, passings, trappeds):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 3, figsize=(15, 4.5))
    styles = {
        "VMEC-Boozer": ("k-", 1.8),
        "VMEC chartmap": ("C0--", 1.4),
        "GVEC chartmap": ("C3:", 2.0),
    }

    ax = axes[0]
    for key, values in totals.items():
        style, width = styles.get(key, ("-", 1.5))
        ax.plot(t * 1e3, values, style, lw=width, label=key)
    ax.set_xlabel("time [ms]")
    ax.set_ylabel("confined fraction")
    ax.set_title("Total confined")
    ax.legend()
    ax.set_ylim(-0.05, 1.05)

    ax = axes[1]
    for key, values in passings.items():
        style, width = styles.get(key, ("-", 1.5))
        ax.plot(t * 1e3, values, style, lw=width, label=f"{key} passing")
    for key, values in trappeds.items():
        style, width = styles.get(key, ("-", 1.2))
        ax.plot(t * 1e3, values, style, lw=max(width - 0.4, 0.8), alpha=0.6,
                label=f"{key} trapped")
    ax.set_xlabel("time [ms]")
    ax.set_ylabel("confined fraction")
    ax.set_title("Passing + Trapped")
    ax.legend(fontsize=8)
    ax.set_ylim(-0.05, 1.05)

    ax = axes[2]
    ref_key = "VMEC-Boozer"
    for key, values in totals.items():
        if key == ref_key:
            continue
        style, width = styles.get(key, ("-", 1.5))
        ax.semilogy(t * 1e3, np.abs(totals[ref_key] - values) + 1e-16,
                    style, lw=width, label=f"{key} - {ref_key}")
    ax.set_xlabel("time [ms]")
    ax.set_ylabel("|difference|")
    ax.set_title("Confined fraction difference")
    ax.legend(fontsize=8)

    fig.suptitle(f"E2E confined fractions: {name}", fontsize=14)
    fig.tight_layout()
    outpath = os.path.join(outdir, f"e2e_{name}.png")
    fig.savefig(outpath, dpi=150)
    print(f"  Saved {outpath}")


def main():
    for path, label in [(SIMPLE_X, "simple.x"), (TOOL_X, "export tool")]:
        if not os.path.exists(path):
            print(f"Missing {label}: {path}")
            sys.exit(1)

    outdir = "/tmp/boozer_chartmap_e2e"
    if os.path.exists(outdir):
        shutil.rmtree(outdir)
    os.makedirs(outdir)

    all_pass = True
    for eq in EQUILIBRIA:
        print(f"\n=== {eq['name']} (trace_time={eq['trace_time']}) ===")
        if not run_single_equilibrium(eq, outdir):
            all_pass = False

    print()
    if all_pass:
        print("ALL EQUILIBRIA PASSED")
    else:
        print("SOME EQUILIBRIA FAILED")
        sys.exit(1)


if __name__ == "__main__":
    main()
