name: docs

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-docs:
    if: github.ref != 'refs/heads/gh-pages'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install documentation dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r docs/requirements.txt

      - name: Build Sphinx docs
        run: sphinx-build -b html docs docs/_build/html

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html

      - name: Determine destination directory
        if: github.event_name == 'push'
        id: destination
        run: |
          REF_NAME="${GITHUB_REF_NAME}"
          if [ "$REF_NAME" = "main" ]; then
            DEST_DIR="latest"
          else
            DEST_DIR="branches/${REF_NAME//\//-}"
          fi
          echo "dest_dir=${DEST_DIR}" >> $GITHUB_OUTPUT

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/html
          destination_dir: ${{ steps.destination.outputs.dest_dir }}
          keep_files: true
